dataset:
  class_name: SimpleDataset
  module_path: track2.datasets.simple_dataset
  datasets:
  - dataset_type: train
    data_root_dir: /root/autodl-tmp/data/Track2
    data_file_path: mixed.txt
    neg_num: 10
    pipeline:
    - name: SimpleProcessor
      config:
        run_type: train
        feat_root_dir: /root/autodl-tmp/data/Track2/feat/bert/mixed/
  - dataset_type: val
    data_root_dir: /root/autodl-tmp/data/Track2
    data_file_path: test.txt
    pipeline:
    - name: SimpleProcessor
      config:
        run_type: val
        feat_root_dir: /root/autodl-tmp/data/Track2/feat/bert/test/
model:
  class_name: SimpleModel
  module_path: track2.models.simple_model
  model:
    score_k: 0
    hidden_size: 768
    fc_dim_times: 4
run_param:
  run_type: train
  log_dir: /root/autodl-tmp/save/ccac/track2/simple_bert_mixed/log/
  log_level: info
  timer_type: all
  meter_category_num: 2
  train_param:
    max_epoch: 100
    batch_size: 128
    log_interval: 10
    val_when_train: true
    eval_when_train: false
    optimizer:
      optimizer_name: sgd
      use_warmup: true
      wamup_iter: 1000
      lr: 0.1
      lr_step:
      - 10000
    loss:
      loss_name: InfoNCE
      negative_mode: paired
    checkpoint:
      ckpt_dir: /root/autodl-tmp/save/ccac/track2/simple_bert_mixed/model/
      save_by_epoch: true
      save_interval: 10
      save_best: false
      save_last: true
  val_param:
    batch_size: 1
  inference_param:
    batch_size: 1