# This Documents and methods are deprecated

dataset:
  class_name: StageTwoDataset
  module_path: track1.datasets.stage_two_dataset
  datasets:
  - dataset_type: train
    data_root_dir: /root/autodl-tmp/data/Track1
    data_file_path: train.txt
    pipeline:
    - name: RobertaProcessor
      config:
        roberta_tokenizer_path: roberta-base
        point_max_length: 256
        sentence_max_length: 256
    - name: StageTwoProcessor
      config: none
  - dataset_type: val
    data_root_dir: /root/autodl-tmp/data/Track1
    data_file_path: test.txt
    pipeline:
    - name: RobertaProcessor
      config:
        roberta_tokenizer_path: roberta-base
        point_max_length: 256
        sentence_max_length: 256
    - name: StageTwoProcessor
      config: none
model:
  class_name: StageTwoModel
  module_path: track1.models.stage_two_model
  model:
    encoder_type: roberta
    encoder_path: roberta-base
run_param:
  run_type: train
  log_dir: /root/autodl-tmp/save/ccac/track1/stage_two/log/
  log_level: info
  timer_type: all
  meter_category_num: 2
  train_param:
    max_epoch: 10
    batch_size: 2
    log_interval: 100
    val_when_train: true
    eval_when_train: true
    optimizer:
      optimizer_name: sgd
      use_warmup: true
      wamup_iter: 1000
      lr: 0.001
      lr_step:
      - 1000
    loss:
      loss_name: CrossEntropyLoss
    checkpoint:
      ckpt_dir: /root/autodl-tmp/save/ccac/track1/stage_two/model/
      save_by_epoch: false
      save_interval: 1
      save_best: false
      save_last: true
  val_param:
    batch_size: 1
  inference_param:
    batch_size: 1