
dataset:
  class_name: BaseDataset
  module_path: track2.datasets.base_dataset
  datasets:
  - dataset_type: train
    data_root_dir: /root/autodl-tmp/data/qnli
    data_file_path: extra.txt
    pipeline:
    - name: RobertaProcessor
      config:
        roberta_tokenizer_path: roberta-base
        point_max_length: 256
        sentence_max_length: 256
    - name: LabelProcessor
      config: none

model:
  class_name: BaseModel
  module_path: track2.models.base_model
  model:
    encoder_type: roberta
    encoder_path: roberta-base
run_param:
  run_type: train
  log_dir: /root/autodl-tmp/save/ccac/qnli/finetune/log/
  log_level: info
  timer_type: all
  meter_category_num: 2
  train_param:
    max_epoch: 10
    batch_size: 16
    log_interval: 100
    val_when_train: false
    eval_when_train: true
    finetune: true
    encoder_save_path: /root/autodl-tmp/save/ccac/qnli/
    optimizer:
      optimizer_name: sgd
      use_warmup: true
      wamup_iter: 1000
      lr: 0.00002
      lr_step:
      - 100000
    loss: 
      loss_name: CrossEntropyLoss
    checkpoint:
      ckpt_dir: /root/autodl-tmp/save/ccac/qnli/finetune/model/
      save_by_epoch: false
      save_interval: 1
      save_best: false
      save_last: true
  val_param:
    batch_size: 1
  inference_param:
    batch_size: 1