

dataset:
  class_name: BaseDataset
  module_path: track1.datasets.base_dataset
  datasets:
  - dataset_type: train
    data_root_dir: /root/autodl-tmp/data/Track1
    data_file_path: train.txt
    pipeline:
    - name: BertProcessor
      config:
        bert_tokenizer_path: bert-base-uncased
        point_max_length: 15
        sentence_max_length: 260
    - name: LabelProcessor
      config: none
  - dataset_type: val
    data_root_dir: /root/autodl-tmp/data/Track1
    data_file_path: dev.txt
    pipeline:
    - name: BertProcessor
      config:
        bert_tokenizer_path: bert-base-uncased
        point_max_length: 15
        sentence_max_length: 260
        sentence_pos_max_length: 
    - name: LabelProcessor
      config: none
model:
  class_name: BaseModel
  module_path: track1.models.base_model
  model:
    bert:
      hidden_size: 768
    bert_path: bert-base-uncased
run_param:
  run_type: train
  log_dir: /root/autodl-nas/save/ccac/track1/baseline/log/
  log_level: info
  timer_type: all
  train_param:
    max_epoch: 10
    batch_size: 16
    log_interval: 100
    optimizer:
      optimizer_name: sgd
      use_warmup: true
      wamup_iter: 1000
      lr: 0.001
      lr_step:
      - 3
    loss: 
      loss_name: CrossEntropyLossWeighted
      weight:
      - 7.034
      - 0.030
      - 2.936
    checkpoint:
      ckpt_dir: /root/autodl-nas/save/ccac/track1/baseline/model/
      save_by_epoch: false
      save_best: True
  val_param:
    batch_size: 1
  inference_param:
    batch_size: 1