
dataset:
  class_name: ContrastiveDataset
  module_path: track1.datasets.contrastive_dataset
  datasets:
  - dataset_type: train
    data_root_dir: /root/autodl-tmp/data/Track1
    data_file_path: train.txt
    pipeline:
    - name: ContrastiveRobertaProcessor
      config:
        roberta_tokenizer_path: roberta-base
        point_max_length: 512
        sentence_pos_max_length: 512
        sentence_neg_max_length: 512
  - dataset_type: val
    data_root_dir: /root/autodl-tmp/data/Track1
    data_file_path: dev.txt
    pipeline:
    - name: ContrastiveRobertaProcessor
      config:
        roberta_tokenizer_path: roberta-base
        point_max_length: 512
        sentence_pos_max_length: 512
        sentence_neg_max_length: 512
model:
  class_name: ContrastiveModel
  module_path: track1.models.contrastive_model
  model:
    encoder_type: roberta
    encoder_path: roberta-base
    frozen_encoder: true
    fc_dim_times: 4
run_param:
  run_type: train
  log_dir: /root/autodl-tmp/save/ccac/track1/contrastive_roberta/log/
  log_level: info
  timer_type: all
  meter_category_num: 2
  train_param:
    max_epoch: 100
    batch_size: 128
    log_interval: 30
    val_when_train: false
    eval_when_train: false
    optimizer:
      optimizer_name: sgd
      use_warmup: true
      wamup_iter: 100
      lr: 0.1
      lr_step:
      - 100
    loss: 
      loss_name: InfoNCE
      negative_mode: paired
    checkpoint:
      ckpt_dir: /root/autodl-tmp/save/ccac/track1/contrastive_roberta/model/
      save_by_epoch: true
      save_interval: 10
      save_best: false
      save_last: true
  val_param:
    batch_size: 1
  inference_param:
    batch_size: 1