dataset:
  class_name: ContrastiveDataset
  module_path: track1.datasets.contrastive_dataset
  datasets:
  - dataset_type: train
    data_root_dir: /root/autodl-tmp/data/Track1
    data_file_path: train.txt
    pipeline:
    - name: BertProcessor
      config:
        bert_tokenizer_path: bert-base-uncased
        point_max_length: 512
        sentence_max_length: 512
    - name: DualLabelProcessor
      config: none
  - dataset_type: val
    data_root_dir: /root/autodl-tmp/data/Track1
    data_file_path: dev.txt
    pipeline:
    - name: BertProcessor
      config:
        bert_tokenizer_path: bert-base-uncased
        point_max_length: 256
        sentence_max_length: 256
    - name: DualLabelProcessor
      config: none
model:
  class_name: ContrastiveClassificationHead
  module_path: track1.models.heads.contrastive_classification_head
  model:
    score_k: 0.5
    encoder_type: bert
    encoder_path: bert-base-uncased
    frozen_encoder: true
    fc_dim_times: 4
run_param: 
  run_type: val
  log_dir: /root/autodl-tmp/save/ccac/track1/contrastive_lr_01/log/
  log_level: info
  timer_type: all
  resume_file: /root/autodl-tmp/save/ccac/track1/contrastive_lr_01/model/epoch_last.ckpt
  meter_category_num: 2
  train_param:
    max_epoch: 100
    batch_size: 128
    log_interval: 30
    val_when_train: false
    eval_when_train: false
    optimizer:
      optimizer_name: sgd
      use_warmup: true
      wamup_iter: 100
      lr: 0.1
      lr_step:
      - 100
    loss: 
      loss_name: InfoNCE
      negative_mode: paired
    checkpoint:
      ckpt_dir: /root/autodl-tmp/save/ccac/track1/contrastive_lr_01/model/
      save_by_epoch: true
      save_interval: 10
      save_best: false
      save_last: true
  val_param:
    batch_size: 1
  inference_param:
    batch_size: 1